apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-deploy
  labels:
    purpose: learning
  namespace: test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      type: create
  template:
    metadata:
      name: httpd
      labels:
        devops: '18'
        company: talent
        type: create
    spec:
      containers:
      - name: httpd
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 5Mi
          limits:
            memory: 10Mi


